categories:
- name: Вітаміни
  products:
  - name: Nutrilite™ Вітамін D, 60 таб.
    price: 450
    description: |-
      Nutrilite™ Вітамін D, 60 таб.
      

    media: products/вітаміни/nutrilite_вітамін_d_60_таб.jpeg