web_scraping:
  # URL початкової сторінки для збору даних
  start_page: "https://rozetka.com.ua/ua/tablets/c130309/"

  token: ""
  
  product_link_selector: "a.product-link.goods-tile__heading"
  
  product_name_selector: "h1.title__font"
  
  product_price_selector: "p.product-price__big"
  
  product_parameters: "div.product-about__sticky p.mt-4"

  # product_description_selector: ""

  product_category: "tablets"
  
  product_image_selector: "img.image"

  media_catalog: "media"